### ISSUE TITLE
BANCO DE DADOS

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [douglascarlos-dev/Clientes-Gestor#11]
ALGUÉM TERIA O BANCO DE DADOS EM ARQUIVO .SQL?

**Comment by douglascarlos-dev** [comment]
> 

https://github.com/douglascarlos-dev/Clientes-Gestor/blob/main/pgmodeler/sql12.0.sql

**Comment by CentroEducacional-CEC** [comment]
Obrigado!
